# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
    # - run: cd website && npm run build

  test-python:
    working_directory: ~.
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: themattrix/tox

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    steps:
      - checkout
      - run: 
          name: Running Tox Tests
          command: cd easy_api && tox

  deploy-docs:
    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "robdox@users.noreply.github.com"
            git config --global user.name "robdox"
            echo "machine github.com login robdox password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=robdox CURRENT_BRANCH=gh-pages npm run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test-python
