# Generated by Django 2.0 on 2018-08-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAPI', '0004_modelapi'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateWidgetAPI',
            fields=[
                ('modelapi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EasyAPI.ModelAPI')),
            ],
            bases=('EasyAPI.modelapi',),
        ),
        migrations.CreateModel(
            name='PublicWidgetAPI',
            fields=[
                ('modelapi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EasyAPI.ModelAPI')),
            ],
            bases=('EasyAPI.modelapi',),
        ),
    ]
