# Generated by Django 2.0 on 2018-08-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_privatepurchaseapi_publicpurchaseapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivatePurchaseAPI',
        ),
        migrations.DeleteModel(
            name='PublicPurchaseAPI',
        ),
    ]
