COLORS = (
    ('black', 'Black'),
    ('blue', 'Blue'),
    ('brown', 'Brown'),
    ('green', 'Green'),
    ('orange', 'Orange'),
    ('red', 'Red'),
    ('red_orange', 'Red Orange'),
    ('sky_blue', 'Sky Blue'),
    ('violet', 'Violet'),
    ('white', 'White'),
    ('yellow', 'Yellow'),
    ('yellow_green', 'Yellow Green'),
)

SIZES = (
    ('small', 'Small'),
    ('medium', 'Medium'),
    ('large', 'Large'),
    ('extra_large', 'Extra Large'),
)

SHAPES = (
    ('rectangle', 'Rectangle'),
    ('ellipse', 'Ellipse'),
    ('diamond', 'Diamond'),
    ('trapezoid', 'Trapezoid'),
    ('parallelogram', 'Parallelogram'),
    ('triangle', 'Triangle'),
    ('circle', 'Circle'),
)
STATES = (
    ('Alabama'),
    ('Alaska'),
    ('Arizona'),
    ('Arkansas'),
    ('California'),
    ('Colorado'),
    ('Connecticut'),
    ('Delaware'),
    ('Florida'),
    ('Georgia'),
    ('Hawaii'),
    ('Idaho'),
    ('Illinois'),
    ('Indiana'),
    ('Iowa'),
    ('Kansas'),
    ('Kentucky'),
    ('Louisiana'),
    ('Maine'),
    ('Maryland'),
    ('Massachusetts'),
    ('Michigan'),
    ('Minnesota'),
    ('Mississippi'),
    ('Missouri'),
    ('Montana'),
    ('Nebraska'),
    ('Nevada'),
    ('New Hampshire'),
    ('New Jersey'),
    ('New Mexico'),
    ('New York'),
    ('North Carolina'),
    ('North Dakota'),
    ('Ohio'),
    ('Oklahoma'),
    ('Oregon'),
    ('Pennsylvania'),
    ('Rhode Island'),
    ('South Carolina'),
    ('South Dakota'),
    ('Tennessee'),
    ('Texas'),
    ('Utah'),
    ('Vermont'),
    ('Virginia'),
    ('Washington'),
    ('West Virginia'),
    ('Wisconsin'),
    ('Wyoming'),
)

GENDERS = (
    ('M'),
    ('F'),
)
