# Generated by Django 2.0 on 2018-07-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='EasyAPI',
        ),
    ]
