# Generated by Django 2.0 on 2018-07-31 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAPI', '0002_auto_20180731_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelAPI',
        ),
    ]
