# Generated by Django 2.0 on 2018-08-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EasyAPI', '0003_delete_modelapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
