# Generated by Django 2.0 on 2018-08-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180804_0143'),
        ('widgets', '0003_auto_20180804_0143'),
        ('purchases', '0003_auto_20180804_0143'),
        ('EasyAPI', '0004_modelapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelAPI',
        ),
    ]
