# Generated by Django 2.0 on 2018-08-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_privatecustomerapi_publiccustomerapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateCustomerAPI',
        ),
        migrations.DeleteModel(
            name='PublicCustomerAPI',
        ),
    ]
